### ISSUE TITLE
can not find ws2.wasm

### ISSUE THREAD

**Issue by swtgeo** [akhenakh/ws2#3]

**Comment by akhenakh** [comment]
Download or clone the project and type `make ws2.wasm`

**Comment by mrsun12** [comment]
Excuse me, i run this project in ubuntu,but i met this problem, and i can not find a useful method:
GOARCH=wasm GOOS=js go build -o htdocs/ws2.wasm main.go
cmd/go: unsupported GOOS/GOARCH pair js/wasm
Makefile:9: recipe for target 'ws2.wasm' faild

**Comment by akhenakh** [comment]
You need go version >= 1.11

**Comment by swtgeo** [comment]
Thank you so much! I have solved.
